# Generated by Django 5.2.7 on 2025-10-08 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_tag_product_is_available_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 8, 14, 3, 25, 132561)),
        ),
    ]
