# Generated by Django 5.2.7 on 2025-10-14 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_order_date_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 14, 12, 51, 23, 355818)),
        ),
    ]
